### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ivanovd** [rmcgirr83/phpBB-3.1-applicationform#1]
Is it possible in addition to creating a topic to add a Poll to it?

For example the question of the poll would be: "Accept the application?"
Possible answers: "Yes" or "No"

**Comment by rmcgirr83** [comment]
Sure, edit the first topic and put in a poll.

**Comment by ivanovd** [comment]
I've been doing that manually, buy my question was if that can be done automatically and to have an option to control that via ACP settings of the extension?

**Comment by rmcgirr83** [comment]
Anything is possible but I won't be adding that.  One would have to set the question and answers for the poll.
