### ISSUE TITLE
Post to a thread rather than create new

### ISSUE THREAD

**Issue by ncc-1709** [rmcgirr83/phpBB-3.1-applicationform#2]
Hi
is there any way of setting this so it posts new forms into the same thread instead of making a new thread each time?

many thanks

**Comment by rmcgirr83** [comment]
No, it isn't possible as there is no way for the extension to know what the original topic id was of the first posting.

**Comment by ncc-1709** [comment]
darn, on VB you can select forum id or thread id for the post to go into. was hoping this could be tweeked to do the same
