### ISSUE TITLE
[3.2.0] text gets parsed as htmlentities

### ISSUE THREAD

**Issue by Mickroz** [rmcgirr83/phpBB-3.1-applicationform#3]
on phpBB 3.2.0-RC1 with php 5.6.15 text gets parsed as htmlentities.
`A user, &lt;strong&gt;&lt;a href="./../memberlist.php?mode=viewprofile&amp;u=2" style="color: #AA0000;" class="username-coloured"&gt;Mickroz&lt;/a&gt;&lt;/strong&gt;, has applied with the following information using the application form.&lt;br /&gt;&lt;br /&gt;<span style="font-weight: bold">Real name</span>: test&lt;br /&gt;<span style="font-weight: bold">Applying for</span>: Moderator&lt;br /&gt;<span style="font-weight: bold">Reason for applying:</span> <blockquote class="uncited"><div> testestest</div></blockquote>`

**Comment by rmcgirr83** [comment]
Can't reproduce this.  Installed a fresh 3.2 forum, installed the application form extension and it displays fine.
![noname](https://cloud.githubusercontent.com/assets/179079/20093450/c8a744b2-a56a-11e6-88d3-bac6e34adf1b.jpg)

**Comment by Mickroz** [comment]
thats weird, i don't have those last two.
ill see if i can reproduce it again Rich.

**Comment by Mickroz** [comment]
Ok, fixed it, i thought i had downloaded from here, but i got it from phpBB.com, so it's the version for 3.1.
After downloading from github it worked like it should.

**Comment by Mickroz** [comment]
btw, i still don't have those 2 last lines.

**Comment by rmcgirr83** [comment]
Those last two lines are not from the code here and should be ignored

**Comment by Mickroz** [comment]
Ok, then it works  :D
