### ISSUE TITLE
Nickname populated instead of real name

### ISSUE THREAD

**Issue by ivanovd** [rmcgirr83/phpBB-3.1-applicationform#6]
**Board version:** 3.2.0
**PHP version:** 7.0.14
**Ext version:** 1.0.7

**Issue:**
I don't have a real name extension enabled, however, the ext autopopulates the nickname in the field and you cannot change it as the text box is disabled. I tried to workaround that by editing styles/prosilver/template/appform_body.html and removing `<!-- IF not S_EMAIL_NEEDED -->disabled<!-- ENDIF -->` from the name input and setting value ="" or even removing it.

However after submitting the form with the real name entered it is still posted with the nickname.
![maxthonsnap20170530171832](https://cloud.githubusercontent.com/assets/4889583/26587833/26a5f0f4-455c-11e7-8f4b-c6da9d628748.png)
![maxthonsnap20170530171817](https://cloud.githubusercontent.com/assets/4889583/26587832/26a5b01c-455c-11e7-9595-87baab2dae5d.png)
![maxthonsnap20170530171446](https://cloud.githubusercontent.com/assets/4889583/26587834/26a9ea10-455c-11e7-9779-7aaf16ae5129.png)

**Comment by rmcgirr83** [comment]
https://github.com/rmcgirr83/phpBB-3.1-applicationform/blob/master/styles/prosilver/template/appform_body.html#L12

along with

https://github.com/rmcgirr83/phpBB-3.1-applicationform/blob/master/controller/main_controller.php#L114

**Comment by rmcgirr83** [comment]
This is now completely fixed.
